language: node_js
notifications:
  email: false
  slack:
    secure: lZDArfLyCDDGPfDIBNneC7u+89kKld75Reut0vc15rJFTMTZs+ETBqEcY7YO+sTuHXJqbtowO2UXPlpFOAwsClEKOojlpZ4TIx6XSEY/K5D/r3LXYYeDTxdLmUvD/fNsgjQ1MEb0yzll/ov1x07H7mvzj8dwKGgerRBaAdbP9zUVxnPcFE6k/d+YxmHoJ5Iww37JZKNWkqP2rBXHVhIQbJyDe3dbFMbpqO2txhc11RIja/ySdZazuVHSriT/K+gQEhJ18TzjvxGY7cJ2BVZFF8bcTnaj23kW2CxJZY8leiTn5E355KZtnsNaDmvg0QO+XgtGlkTxQNgWhhxRT9PpCUlpLCN5Bp1BhBeoEugJvrCcrhviJq96wvlAGw+m89R/0ePRB2rN4zJRNMU0luae9Ic0o/PJ7fXA1a6Gtr7f0dyfW7Xv0FE9i7BcQAAbgFjjQhrXd0Of2sk7vGLDLbmee48cJ/ZOWObgGpA5r6zlB8OYVjMeobUN4fmQWls7kpZF6ecrnNaXlR0c1FYNeTP1yJq1X2NYIUiGgFW8pqHi050SOiFDOdL9NboCI2HTk08JRtCkTLLaiyW5ODvFMD5kaY5GE4fMDFlm5zTYerzFUBlb2KQ5UH75FwFyHSVau4AZ789ygHyIxvD+amCtf/yQXp8+YSHgBK4qCGepHE9MjJY=
node_js:
- 6.9.2
sudo: false
cache:
  directories:
  - node_modules
git:
  submodules: false
before_install:
- npm install -g grunt-cli
- grunt --version
script:
- grunt
